version: '3.8'

services:
  ijt_web_client:
    image: python:3.14-slim
    container_name: ijt_web_client
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      - IS_DOCKER=true
      - PYTHONUNBUFFERED=1
    command: ["python", "setup_project.py", "--force_full"]
    restart: unless-stopped